(ns publichouse.profile.cjo
  (:use publichouse.profile.util)
  (:require [net.cgrand.enlive-html :as e]))

;;;; A transformation profile for Cambridge Journals Online
;;;; I will be using the American Political Science Review articles to
;;;; create this profile, but I expect it to travel to other journals
;;;; published by Cambridge.

;;; The title is in the next h3 element after the "Research Article"
;;; For other type of documents, this might fail
(defn- title
  [html]
  (first
   (e/texts
    (e/select 
     html
     [(e/left [:h3 (e/has [(e/text-pred #(= "Research Article" %))])])]))))

(defn- author
  [html]
  (apply str (filter #(not (= " " %)) (e/select html [:h3.author :> e/text-node]))))

(defn transform
  "Transform HTML from Cambridge Journals Online into the profile data specification"
  [{html :content}]
  ;; Some features of CJO HTML versions:
  ;; 1. Repeating tables of contents (which can be deleted)
  ;; 2. Section headings use <p> instead of <hX> in some cases
  ;; 3. Figures and tables are generated by JavaScript
  (let [article nil]
    {:title (title html)
     :author (author html)}))
            
